# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.TimeField(),
        ),
    ]
