# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171217_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
