# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20171220_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('UKR', 'Ukraine'), ('BE', 'Belarus'), ('USA', 'USA'), ('GER', 'Germany'), ('UK', 'United Kingdom'), ('PO', 'Poland')], max_length=255),
        ),
    ]
