# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20171218_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text',
            new_name='comment',
        ),
    ]
