# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171218_2136'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
