# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
