# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20171219_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_post',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
            preserve_default=False,
        ),
    ]
