# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20171219_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(db_tablespace=120),
        ),
    ]
